spring:
  application:
    name: manager
  influx:
    password: cadvisor
    user: cadvisor
    url: http://config.com:8086
  redis:
    host: manager.com
    port: 6379

server:
  port: 8888
  compression:
    enabled: true



